# Generated by Django 5.1 on 2024-08-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='done',
        ),
    ]
