# Generated by Django 5.1 on 2024-08-26 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0002_estado_proceso'),
        ('tareas', '0002_alter_tareas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.estado'),
        ),
    ]
