# Generated by Django 5.1 on 2024-08-24 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_remove_tareas_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
